### PR TITLE
Fix and flesh out Concourse stories

### PR DESCRIPTION
**Pull request by dsabeti**
- Fixes a bunch of dead links caused by the Concourse team moving from concourse.ci to concourse-ci.org
- Uses a different BOSH director setup. Specifically, instead of hacking the Concourse deployment manifest to piggyback on the GCP load balancers created for CF, the story instructs the user to simply run `bbl up` to get an additional fresh BOSH director with dedicated Concourse load balancer
- Includes an "extra credit" story for setting up DNS to point to the Concourse deployment
- Adds some more detail to the pipeline and git-resource configuration

Addresses:
- https://github.com/pivotal-cf/onboarding/issues/120
- https://github.com/pivotal-cf/onboarding/issues/121

### CODE REVIEW

**Comment by dprotaso** [comment]
Would you consider not using `bbl` and having people use docker as per the concourse homepage

```
$ wget https://concourse-ci.org/docker-compose.yml
$ docker-compose up
```

**Comment by dprotaso** [comment]
Also I just found out about this - https://concoursetutorial.com/

**Comment by dsabeti** [comment]
Hey @dprotaso, I'm open to it, but it seems that there's also a separate [`concourse_local.prolific` in this repo](https://github.com/pivotal-cf/onboarding/blob/master/concourse_local.prolific) -- would it make more sense to put the docker workflow in those stories?

**Comment by benmoss** [comment]
Yeah I have been recommending my onboarders to just do the Stark & Wayne tutorial. I think it's a much better ground-up introduction to Concourse than this repo's material. The "Add a docker-image resource to the pipeline" story is just plain nonsense as far as I can understand it. I think that doing another BOSH deploy is just kinda pointless at this point, if you've done the CF tutorials you've already seen how annoying it is, so not sure what value it adds here. It seems the main value is learning the power of Concourse abstractions and not deploying yet another manifest/bbl director.

I guess I would opt for dropping the bosh instructions entirely, and maybe just directing people to the Stark and Wayne tutorial.

**Comment by dsabeti** [comment]
Ok, thanks for this context and feedback, everyone. After reading through Ben's answer, I think it definitely makes sense to focus on the Concourse abstractions rather than setting it up. Do y'all think it would make more sense to consolidate the two Concourse epics (`concourse.prolific` and `concourse_local.prolific`) into a single epic that uses docker-compose and the Stark and Wayne tutorial?

**Comment by dprotaso** [comment]
I’m onboard with that

**Comment by dsabeti** [comment]
Hey @dprotaso and @benmoss. I've made the changes we discussed. Let me know what you think.

**Comment by dprotaso** [comment]
Do you still need these stories in `concourse.prolific` if we link to the tutorial
1. Create a pipeline with a single job 
1. Add a Git resource to the pipeline

**Comment by dsabeti** [comment]
Yeah, I was hoping that folks would still use those stories as guidance about what they should study up on, but I think the better solution is what I've just added: a list of the topics they should go through at the least, plus an invitation to keep going on to other topics if they want.

**Review by benmoss — APPROVED** [review]
Awesome, thanks :)

**Pull request merged**
