### PR TITLE
Add story for running a task

### PR DESCRIPTION
**Pull request by Gerg**

### CODE REVIEW

**Comment by dsabeti** [comment]
This looks like a good thing to include in Onboarding, but I don't think the doc that's linked in there provides the participants with a sample app that they can use to actually run the task. It would also be nice to give a little bit of an explanation about the differences and relationships between apps and tasks.

**Comment by ssapra** [comment]
I was going through the Onboarding this week and after we finished deploying and scaling an app (dora), we also found this same documentation for running a simple task on our dora app. 

I also found it good to tail the logs of the auctioneer to see it respond to a new task.

👍 for this addition to the App Development stories

**Comment by dsabeti** [comment]
In general, I think this story would benefit from providing a link to an app that has a `db:migrate` rake task, so that participants can just follow the public documentation.

@ssapra, which task did you run against dora? The doc talks about `rake db:migrate`, but dora doesn't use a database.

**Comment by ssapra** [comment]
@dsabeti I believe I ran something really simple like `echo "Hello World"; sleep 10` just to have the task run for a bit and see the status change and see the output in the logs.

**Comment by ljfranklin** [comment]
Based on the above comments I took another pass at writing a task story over here: https://github.com/pivotal-cf/onboarding/pull/163

**Comment by ljfranklin** [comment]
Going to close this PR in favor of https://github.com/pivotal-cf/onboarding/pull/163. Thanks for getting this started @Gerg!

**Pull request closed without merging**
