### PR TITLE
Improved 3 stories in app development flow

### PR DESCRIPTION
**Pull request by Shanfan**

### CODE REVIEW

**Review by suprajanarasimhan — APPROVED** [review]
These improvements will benefit future CF Onboarding students.  Thank you!

**Comment by suprajanarasimhan** [comment]
Hi @bwinter! I was wondering if you might know what additional step I might need to take to merge this PR?

**Comment by bwinter** [comment]
@suprajanarasimhan - ahh, sry, I totally missed this. Feel free to ping me in slack if I miss something like this!

I think as long as you approve the change it should be mergeable, did that not happen?

**Comment by bwinter** [comment]
I just added you as a collaborator. Can you merge now?

**Pull request merged**
